input {
    beats {
        port => 5044
    }
}

filter {
    json {
        source => "message"
    }

    date {
        match => ["time", "UNIX_MS"]
    }
}

output {
    elasticsearch {
        hosts => ["http://elasticsearch:9200"]
        index => "logs-do-sistema-via-logstash-%{+YYYY.MM.dd}"
    }
    stdout {
        codec => rubydebug
    }
}
